const post = window.PROJECT_POSTS.find((item) => item.id === window.POST_ID);
const root = document.getElementById('postRoot');
const title = document.getElementById('postTitle');
const base = document.body.dataset.assetBase || '';
function escapeHtml(value = '') { return String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('\"', '&quot;').replaceAll("'", '&#039;'); }
function assetPath(value = '') { if (!value || /^https?:\/\//.test(value)) return value; return base + value; }
function formatDate(date) { if (!date) return 'Sin fecha'; return new Intl.DateTimeFormat('es-HN', { dateStyle: 'medium' }).format(new Date(date + 'T00:00:00')); }
function youtubeEmbedUrl(url = '') { const match = String(url).match(/(?:v=|youtu\.be\/|embed\/|shorts\/)([A-Za-z0-9_-]{6,})/); return match ? 'https://www.youtube.com/embed/' + match[1] : ''; }
if (!post) { root.innerHTML = '<div class="empty-state"><h1>Publicación no encontrada</h1><p>Volvé al listado de proyectos.</p></div>'; } else { title.textContent = post.title + ' — Ingeniería Militar en Mecatrónica'; const videos = (post.youtube || []).map(youtubeEmbedUrl).filter(Boolean).map((url) => '<div class="video-frame"><iframe src="' + escapeHtml(url) + '" title="' + escapeHtml(post.title) + '" allowfullscreen loading="lazy"></iframe></div>').join(''); root.innerHTML = '<a class="back-link" href="../projects.html">← Volver a proyectos</a><article class="post-detail standalone-post"><header class="post-header"><span class="section-tag">' + escapeHtml(post.category || 'Publicación') + '</span><h1>' + escapeHtml(post.title) + '</h1><div class="post-meta"><span>' + escapeHtml(post.author || 'Autor pendiente') + '</span><span>' + formatDate(post.date) + '</span></div></header>' + (post.coverImage ? '<img class="post-cover" src="' + escapeHtml(assetPath(post.coverImage)) + '" alt="' + escapeHtml(post.title) + '">' : '') + '<div class="post-content">' + (post.content || []).map((paragraph) => '<p>' + escapeHtml(paragraph) + '</p>').join('') + '</div>' + (videos ? '<div class="post-media"><h3>Videos</h3>' + videos + '</div>' : '') + ((post.images || []).length ? '<div class="post-gallery">' + post.images.map((image) => '<img src="' + escapeHtml(assetPath(image)) + '" alt="' + escapeHtml(post.title) + '" loading="lazy">').join('') + '</div>' : '') + ((post.links || []).length ? '<div class="post-links"><h3>Recursos</h3>' + post.links.map((link) => '<a href="' + escapeHtml(link.url) + '" target="_blank" rel="noopener noreferrer">' + escapeHtml(link.label) + '</a>').join('') + '</div>' : '') + '</article>'; }
